workflows:
  flutter-build:
    name: Flutter build for Android and Web
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/web/**
